[project]
name = "seleniumqt"
version = "0.0.0" # Cannot be bothered to update this, might do so when updates become more scarce.
authors = [
    {name = "Ansh Mathur", email = "worldanvilbild.seleniumqt@gmail.com"},
    {name = "Ansh Mathur Alt Email", email="infiplexity.seleniumqt@gmail.com"} # an alt email address.
]
description = "fully undetectable and automated selenium like api for controlling a QtWebEngine Browser Instance."
readme = "README.md"
license = {file="LICENSE"}
requires-python='>=3.10'
keywords = [
    "selenium",
    "undetectable",
    "chromedriver",
    "qt",
    "PyQt"
]

[project.scripts]
seleniumqt = 'seleniumqt.__main__:main'

[tool.black]
line-length = 79

[tool.ruff]
line-length = 79
# TODO: THIS.

[toolmypy]
# TODO: THIS.

[build-system]
requires = ["setuptools>=66.1", 'wheel']
build-backend = "setuptools.build_meta"